README.md, substrait_consumer/conftest.py, substrait_consumer/tests/adhoc/ibis_expr.py, substrait_consumer/tests/adhoc/query.sql, substrait_consumer/tests/adhoc/test_adhoc_expression.py, substrait_consumer/tests/functional/extension_functions/test_boolean_functions.py
test for generating substrait plans from supported producers when given a SQL query or Ibis expression.  Substrait plans can be run against supported consumers as well.
Option to save substrait plan from each producer as json output.
=> feat: test for generating substrait from adhoc sql/ibis

SUPPORT_MATRIX.md, app/substrait_consumer_function_compatibility.py, app/substrait_producer_function_compatibility.py
Test results path needs to be a url in order for streamlit to be able to read it
since streamlit is a third party app.
=> Fix: fix test results path in streamlit app python script

substrait_consumer/conftest.py
Adding back the AceroConsumer to conftest so it can be tested with
=> fix: add aceroconsumer back to conftest

substrait_consumer/functional/queries/sql/relations/write_relations.py, substrait_consumer/functional/write_relation_configs.py, substrait_consumer/tests/functional/relations/test_write_relation.py
No producers currently seem to support generating substrait plans with writes.
Tests will be marked to skip.  Results generation is removed since write do not return results.
=> feat: add write relation tests

substrait_consumer/functional/ddl_relation_configs.py, substrait_consumer/functional/queries/sql/relations/ddl_relations.py, substrait_consumer/tests/functional/relations/test_ddl_relation.py
tests are marked to be skipped for now since no producers can generate
substrait plans properly
=> feat: add ddl relation tests

substrait_consumer/functional/common.py, substrait_consumer/producers/ibis_producer.py, substrait_consumer/producers/isthmus_producer.py, substrait_consumer/producers/producer.py, substrait_consumer/tests/functional/extension_functions/test_substrait_function_names.py
Some producers had an additional parameter `validate` but the interface and the IbisProducer as well as one call site were missing it. This PR introduces that parameter in those places. In also changes the formatting in one of the producers to be consistent with the others.
I have manually test: no test outcome changes. Several tests for the IbisProducer reported a wrong number of arguments before and now fail because the producer cannot handle the test cases.
=> fix: add missing arguments to Producer.produce_substrait

.github/workflows/python_formatting.yml
This is achieved via the Python package `darker`, which checks that all changed lines are formatted with "black" style. The intent is to strike a balance between enforcing a style but not doing one large commit that only reformats everything, which messes up git history. After this CI rule has run for some time, the (hopefully small) remaining part of the code can still be reformatted with black in one commit and black be enforced from that moment of time.
I have done a quick comparison of various formatters and black seems to be the one that results in a formatting that is closest to the current format, so enforcing that in CI seems like the best choice.
Please see this PR as a means to start a discussion. I believe that enforcing a style in CI is a good way to improve readability …
=> ci: set up GH action that enforces black formatting on changed lines

.github/workflows/test.yml
PR #132 changed the definition of Github CI workflows to use the `matrix` feature. If not changed explicitly, the different variants in the matrix are cancelled as soon as the first variant fails. This currently prevents us from knowing which of the systems pass CI. This PR thus sets `fail-fast: false` in order to let all variants in the matrix to run to completion.
=> ci: run all matrix jobs to the end even if others fail

substrait_consumer/tests/adhoc/test_adhoc_expression.py, substrait_consumer/tests/functional/extension_functions/test_approximation_functions.py, substrait_consumer/tests/functional/extension_functions/test_arithmetic_decimal_functions.py, substrait_consumer/tests/functional/extension_functions/test_arithmetic_functions.py, substrait_consumer/tests/functional/extension_functions/test_boolean_functions.py, substrait_consumer/tests/functional/extension_functions/test_comparison_functions.py, substrait_consumer/tests/functional/extension_functions/test_datetime_functions.py, substrait_consumer/tests/functional/extension_functions/test_logarithmic_functions.py, substrait_consumer/tests/functional/extension_functions/test_rounding_functions.py, substrait_consumer/tests/functional/extension_functions/test_string_functions.py, substrait_consumer/tests/functional/extension_functions/test_substrait_function_names.py, substrait_consumer/tests/functional/relations/test_aggregate_relation.py, substrait_consumer/tests/functional/relations/test_ddl_relation.py, substrait_consumer/tests/functional/relations/test_fetch_relation.py, substrait_consumer/tests/functional/relations/test_filter_relation.py, substrait_consumer/tests/functional/relations/test_join_relation.py, substrait_consumer/tests/functional/relations/test_project_relation.py, substrait_consumer/tests/functional/relations/test_read_relation.py, substrait_consumer/tests/functional/relations/test_set_relation.py, substrait_consumer/tests/functional/relations/test_sort_relation.py, substrait_consumer/tests/functional/relations/test_write_relation.py, substrait_consumer/tests/integration/test_acero_tpch.py, substrait_consumer/tests/integration/test_duckdb_tpch.py, substrait_consumer/tests/integration/test_tpch_plans_valid.py
Many tests use a DuckDB connection as a fixture. That fixture was set to a `class` scope, such that a DuckDB connection was created only once for all tests of a particular class, presumably to speed up tests. However, tests may corrupt the DuckDB instance, making all subsequent tests fail as a result. This lack of reproducibility undermines tests and is far worse than slightly longer-running tests. This PR thus makes all mentioned fixtures function-scoped (by removing the `scope` definition, `function` scope is the default).
=> fix: make DB connection a function-scope fixture

substrait_consumer/context.py, substrait_consumer/producers/datafusion_producer.py, substrait_consumer/producers/duckdb_producer.py, substrait_consumer/tests/integration/test_tpch_plans_valid.py
In several places, some diagnostics of the `substrait-validator` were attempted to deactivate by specifying a minimum level that was higher that the maximum level. This does not work anymore with newer versions of the validator. If attempted, we get failed assertions with the message `min <= max`. This PR instead sets both minimum and maximum level to `info` in these cases, which resolves the broken assertions.
=> fix: deactivate diagnostics of `substrait-validator` correctly.

substrait_consumer/functional/queries/sql/relations/read_relations.py
The previous producer tests for the `VirtualTable` case of `ReadRel`s for DataFusion and DuckDB used SQL constructs using `CREATE TABLE`. This is problematic because those aren't queries -- they don't return results. This PR uses the `SELECT * FROM VALUES` construct that both systems support in one variant or the other. Unfortunately, both systems still don't pass the test: (1) DuckDB has only added support for `FROM VALUES` to their Substrait extension two weeks ago and (2) DataFusion produces a plan that the validator rejects.
=> fix: use `FROM VALUES` in `VirtualTable` producer tests

substrait_consumer/conftest.py, substrait_consumer/consumers/acero_consumer.py, substrait_consumer/consumers/consumer.py, substrait_consumer/consumers/datafusion_consumer.py, substrait_consumer/consumers/duckdb_consumer.py, substrait_consumer/functional/common.py, substrait_consumer/producers/datafusion_producer.py, substrait_consumer/producers/duckdb_producer.py, substrait_consumer/producers/ibis_producer.py, substrait_consumer/producers/isthmus_producer.py, substrait_consumer/producers/producer.py, substrait_consumer/tests/adhoc/test_adhoc_expression.py, substrait_consumer/tests/functional/extension_functions/test_approximation_functions.py, substrait_consumer/tests/functional/extension_functions/test_arithmetic_decimal_functions.py, substrait_consumer/tests/functional/extension_functions/test_arithmetic_functions.py, substrait_consumer/tests/functional/extension_functions/test_boolean_functions.py, substrait_consumer/tests/functional/extension_functions/test_comparison_functions.py, substrait_consumer/tests/functional/extension_functions/test_datetime_functions.py, substrait_consumer/tests/functional/extension_functions/test_logarithmic_functions.py, substrait_consumer/tests/functional/extension_functions/test_rounding_functions.py, substrait_consumer/tests/functional/extension_functions/test_string_functions.py, substrait_consumer/tests/functional/extension_functions/test_substrait_function_names.py, substrait_consumer/tests/functional/relations/test_aggregate_relation.py, substrait_consumer/tests/functional/relations/test_fetch_relation.py, substrait_consumer/tests/functional/relations/test_filter_relation.py, substrait_consumer/tests/functional/relations/test_join_relation.py, substrait_consumer/tests/functional/relations/test_project_relation.py, substrait_consumer/tests/functional/relations/test_read_relation.py, substrait_consumer/tests/functional/relations/test_set_relation.py, substrait_consumer/tests/functional/relations/test_sort_relation.py
This really consists of two semi-independent parts: the PR (1) introduces and abstract class method `name` that is used whenever the name of a producer or consumer is printed (rather than its class name) and it (2) replaces instance tests using string comparison of the name of the class instance with proper `isinstance` tests.
=> feat: improve how producer/consumer names are handled

substrait_consumer/tests/functional/relations/test_aggregate_relation.py
The recent #147 introduced a bug in a skip criterion that skipped over a test that can lead to a crash by negating a test. This PR brings back the logic.
=> fix: bring back correct formulation of skip criterion

substrait_consumer/functional/queries/ibis_expressions/string_functions_expr.py, substrait_consumer/tests/functional/extension_functions/string_snapshots/IbisProducer/ltrim-ibis_outcome.txt, substrait_consumer/tests/functional/extension_functions/string_snapshots/IbisProducer/rtrim-ibis_outcome.txt, substrait_consumer/tests/functional/extension_functions/string_snapshots/IbisProducer/trim-ibis_outcome.txt
This PR fixes the usage of Ibis' `*trim` functions, which do not take any arguments but always remove whitespace instead. Unfortunately, this only changes the error that is produced since `*trim` is currently translated to Substrait correctly (see
ibis-project/ibis-substrait#1224).
=> fix: use correct arguments for Ibis' `*trim` expressions

.github/workflows/support_matrix.yml
This adopts the same way of building and installing Isthmus and its dependencies in the support matrix workflow as in the test workflow, namely using GH actions. The latter had been updated at some point but not the former. The former also used the wrong version of Java, which now made CI fail. (No idea why it didn't break earlier.)
=> ci: install Isthmus using actions in support matrix workflow

substrait_consumer/conftest.py, substrait_consumer/functional/common.py, substrait_consumer/tests/functional/extension_functions/test_approximation_functions.py, substrait_consumer/tests/functional/extension_functions/test_arithmetic_decimal_functions.py, substrait_consumer/tests/functional/extension_functions/test_arithmetic_functions.py, substrait_consumer/tests/functional/extension_functions/test_boolean_functions.py, substrait_consumer/tests/functional/extension_functions/test_comparison_functions.py, substrait_consumer/tests/functional/extension_functions/test_datetime_functions.py, substrait_consumer/tests/functional/extension_functions/test_logarithmic_functions.py, substrait_consumer/tests/functional/extension_functions/test_rounding_functions.py, substrait_consumer/tests/functional/extension_functions/test_sql_producers.py, substrait_consumer/tests/functional/extension_functions/test_string_functions.py, substrait_consumer/tests/functional/relations/test_aggregate_relation.py, substrait_consumer/tests/functional/relations/test_ddl_relation.py, substrait_consumer/tests/functional/relations/test_fetch_relation.py, substrait_consumer/tests/functional/relations/test_filter_relation.py, substrait_consumer/tests/functional/relations/test_join_relation.py, substrait_consumer/tests/functional/relations/test_project_relation.py, substrait_consumer/tests/functional/relations/test_read_relation.py, substrait_consumer/tests/functional/relations/test_set_relation.py, substrait_consumer/tests/functional/relations/test_sort_relation.py, substrait_consumer/tests/functional/relations/test_sql_producers.py, substrait_consumer/tests/functional/relations/test_write_relation.py
This PR is based on and, therefor, includes #156.
This PR removes the indirection through `test_*_functions.py` and `test_*_relation.py` files and uses file globbing on the test definition files for test collection instead. This is the first step in removing the `test_*.py` files alltogether. These files are heavily repetitive while only providing minimum value (adding some metadata and homing some skip definitions, both of which can be done otherwise) and, therefor, a burden for maintainability.
=> feat: remove test_*.py indirection for producer tests 

substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_1/query_01_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_10/query_10_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_11/query_11_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_12/query_12_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_13/query_13_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_14/query_14_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_15/query_15_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_18/query_18_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_19/query_19_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_3/query_03_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_5/query_05_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_6/query_06_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_7/query_07_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_8/query_08_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_tpch/test_substrait_query/test_tpch_sql_9/query_09_outcome.txt, substrait_consumer/tests/integration/test_acero_tpch.py, substrait_consumer/tests/integration/test_duckdb_tpch.py
~~This PR is based on and, therefor, includes #164.~~
The tests didn't previously record the outcome of running TPC-H queries in terms of success but still used assertions. This didn't show up because all queries where the tests got to the point where they could *run* also produced the correct results. However, this is against the philosophy of the repository, so this PR records also successful outcomes.
=> feat: record outcome of running TPC-H queries in case of success

substrait_consumer/tests/integration/test_tpch_plans_valid.py
~~This PR is based on and, therefor, includes #164.~~
The tests ensuring plan validity only recorded the outcome in case of failure, not in case of success. This means that changing a test case from failure outcome to success outcome *without* updating the snapshots did not lead to CI failure, which is against the intention of the CI architecture. This PR adds snapshot tests also in case of valid plans. This does not currently change any outcomes since none of the TPC-H plans passes the validity test.
=> feat: test for outcome in case of success in TPC-H validity tests 

substrait_consumer/tests/integration/snapshots/test_tpch_plans_valid/test_duckdb_substrait_plans_valid/test_tpch_sql_18/test_tpch_sql_18_outcome.txt, substrait_consumer/tests/integration/test_tpch_plans_valid.py
~~This PR is based on and, therefor, includes #168.~~
This PR reuses the plan validation that is part of the `Producer` interface in the tests that check plan validity for the TPC-H queries for DuckDB. This leads to the same result in terms of validity; however, the error class is different in the one error case, so the outcome changes from one error to another for that query.
=> feat: do TPC-H plan validation for DuckDB with `Producer`

substrait_consumer/tests/integration/test_duckdb_on_acero.py, substrait_consumer/tests/integration/test_duckdb_on_duckdb.py, substrait_consumer/tests/integration/test_isthmus_on_acero.py
This PR is based on and, therefor, includes #174.
This PR reads the Substrait plans used to test consumers from the "generation" snapshots rather than producing them from DuckDB on the fly. This makes these tests more similar to the general-purpose pattern of tests with the goal of eventually replacing them with those patterns.
=> feat: read Substrait plans for TPC-H execution tests from snapshots

substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_1/query_01_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_10/query_10_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_11/query_11_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_12/query_12_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_13/query_13_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_14/query_14_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_15/query_15_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_18/query_18_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_19/query_19_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_3/query_03_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_5/query_05_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_6/query_06_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_7/query_07_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_8/query_08_outcome.txt, substrait_consumer/tests/integration/snapshots/test_duckdb_on_duckdb/test_substrait_query/test_tpch_sql_9/query_09_outcome.txt, substrait_consumer/tests/integration/test_duckdb_on_acero.py, substrait_consumer/tests/integration/test_duckdb_on_duckdb.py, substrait_consumer/tests/integration/test_isthmus_on_acero.py
~~This PR depends on and, therefor, includes #175.~~
This PR makes the format of the outcome snapshot files coherent with the new outcome format introduced in #176 for the remaining tests. More precisely, the name of the dictionary entries change from `column_names` to `schema` and from `table` to `data`.
=> feat: make TPC-H outcome format coherent with new outcome format

substrait_consumer/tests/integration/test_duckdb_on_acero.py, substrait_consumer/tests/integration/test_duckdb_on_duckdb.py, substrait_consumer/tests/integration/test_isthmus_on_acero.py
~~This PR depends on and, therefor, includes #178.~~
This PR uses the result snapshots containing the DuckDB results introduced in #178 in order to check for correctness of the consumers in the TPC-H tests. This is one of the final steps before turning this test into calls to the generic test functions.
=> feat: use result snapshot to check TPC-H consumer results

substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q01-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q02-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q03-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q04-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q05-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q06-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q07-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q08-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q09-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q10-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q11-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q12-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q13-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q14-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q15-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q16-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q17-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q18-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q19-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q20-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q21-generate-outcome.txt, substrait_consumer/tests/functional/integration/tpch_snapshots/integration_test_results/q22-generate-outcome.txt, substrait_consumer/tests/integration/test_duckdb_on_acero.py, substrait_consumer/tests/integration/test_duckdb_on_duckdb.py, substrait_consumer/tests/integration/test_isthmus_on_acero.py, substrait_consumer/tests/integration/test_tpch_plans_valid.py
~~This PR depends on and, therefor, includes #179 and #180.~~
This PR creates a new test target that generates references results for the TPC-H consumer tests using DuckDB as a wrapper to `generate_snapshot_results`. That logic had previously been inlined in the various TPC-H tests. This PR also removes that logic from there; the consumer behaviour is thus now tested only against the snapshots generated by the new targets and does not need any reference result produced by DuckDB on the fly.
=> feat: factor out DuckDB result generation of TPC-H tests

substrait_consumer/tests/integration/test_duckdb_on_acero.py, substrait_consumer/tests/integration/test_duckdb_on_duckdb.py, substrait_consumer/tests/integration/test_isthmus_on_acero.py
~~This PR is based on and, therefor, includes #181.~~
This PR implements the TPC-H consumer tests using the generic `substrait_consumer_sql_test` function that the other consumer tests are implemented with. Previous PRs had factored out other test logic from these tests such that they were now equivalent with the generic logic. What remains now from the TPC-H tests is merely glue code, which we can futher merge with the other tests in the next PRs.
=> feat: implement TPC-H consumer tests using generic infra 

substrait_consumer/snapshots/producer/integration/tpch/q06-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q08-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q11-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q12-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q14-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q17-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q18-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q19-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q20-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q22-isthmus_plan.json, substrait_consumer/snapshots/results/integration/tpch/q19-isthmus-duckdb_outcome.txt
This PRupdates the `substrait-java` git submodule to the next commit,
`f15cbabd`, which breaks some of the snapshot tests.
The PR  also updates the plan snapshots of several tests of TPC-H queries
for Isthmus. The plans have, in parts, change substatntially and I have
not verified all changes in detail. However, the version of Calcite that
Isthmus uses has changed in this update, so major plan changes seem
reasonable.
=> chore: update `substrait-java` git submodule to next version 

substrait_consumer/snapshots/producer/integration/tpch/q01-isthmus_plan.json
This commit updates the `substrait-java` git submodule to its latest
verstion as of today, namely v0.50.0.
The PR also updates one plan snapshot of an Isthmus test due to the
version change in this PR. The plan changes the members of an
`intervalDaysToSeconds`, so I suppose it is due to
substrait-io/substrait-java#335, which fixes a bug related to that
message type.
=> chore: update `substrait-java` git submodule to latest version

substrait_consumer/snapshots/producer/integration/tpch/q01-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q03-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q05-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q06-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q07-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q08-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q09-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q10-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q11-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q14-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q17-isthmus_plan.json, substrait_consumer/snapshots/producer/integration/tpch/q19-isthmus_plan.json, substrait_consumer/snapshots/producer/relation/aggregate/aggregate_with_computation-isthmus_plan.json, substrait_consumer/snapshots/producer/relation/aggregate/compute_within_aggregate-isthmus_plan.json, substrait_consumer/snapshots/producer/relation/project/extended_project-isthmus_plan.json
This is the latest version that runs with just one fix. The breaking
change until there is substrait-io/substrait-java#350, which changes
which types are used in some places. Consequently, some of the plans
generated by Isthmus change: in several occasions, the precision and/or
scale of decimal types changes and, in one instance, a new cast to a
decimal type with a different precision is inserted.
=> chore: update `substrait-java` git submodule to v0.51.0 
